name: "generate sample junit artifact"
jobs:
  - job: junit_artifact_generate
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.12"
      - script: |
          cd ./demo
          ls -lR
          pip install -r requirements.txt
          python junit_artifact_generate.py
        displayName: "install deps and run script"
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: "./demo/junit.xml"
          artifact: "junit.xml"
        displayName: "upload artifact"
