name: "generate sample junit artifact"
on:
  workflow_dispatch:
jobs:
  junit_artifact_generate:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: clone repo
        uses: actions/checkout@v4
      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: install deps and run script
        run: |
          cd ./demo
          ls -lR
          pip install -r requirements.txt
          python junit_artifact_generate.py
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./demo/junit.xml
          name: junit.xml
          if-no-files-found: ignore
