name: "generate sample junit artifact"
on:
  workflow_dispatch:
jobs:
  junit_artifact_generate:
    runs-on: ubuntu-latest
    steps:
      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: install deps and run script
        working-directory: demo
        shell: bash
        run: |
          pip install -r requirements.txt
          python junit_artifact_generate.py
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: junit.xml
          path: demo
          if-no-files-found: ignore
